name: Linguagens do GitHub

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  languages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gerar SVG de linguagens
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: linguagens.svg
          base: repositories
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

      - name: Commit do SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add linguagens.svg
          git commit -m "Atualiza estatísticas de linguagens" || echo "Nada para commitar"
          git push
