name: 🚀 Fix and Update Stats

on:
  workflow_dispatch:  # Apenas manual

permissions:
  contents: write

jobs:
  fix-update:
    runs-on: ubuntu-latest
    
    steps:
      # PASSO 1: Checkout com token padrão
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Pega tudo

      # PASSO 2: SEMPRE fazer pull primeiro
      - name: 🔄 Sync with GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Puxa as alterações do GitHub
          git pull origin main --rebase --autostash
          
          # Resolve qualquer conflito automaticamente
          git checkout --ours . || true
          git add .

      # PASSO 3: Criar arquivo simples
      - name: 📊 Create Stats File
        run: |
          # Remove arquivos antigos se existirem
          rm -f STATS.md 2>/dev/null || true
          
          # Cria novo arquivo
          echo "# 📊 Estatísticas do MarcoTuliops22" > STATS.md
          echo "" >> STATS.md
          echo "## 🚀 Atualizado em: $(date '+%d/%m/%Y %H:%M')" >> STATS.md
          echo "" >> STATS.md
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=MarcoTuliops22)" >> STATS.md
          echo "" >> STATS.md
          echo "![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=MarcoTuliops22)" >> STATS.md

      # PASSO 4: Commit e push seguro
      - name: 📤 Safe Commit and Push
        run: |
          # Adiciona apenas o novo arquivo
          git add STATS.md
          
          # Se não houver mudanças, sai
          if git diff --staged --quiet; then
            echo "✅ Nenhuma mudança necessária"
            exit 0
          fi
          
          # Commit
          git commit -m "📈 Atualizar estatísticas - $(date '+%d/%m/%Y')" || echo "Commit falhou, continuando..."
          
          # Puxa novamente antes de push
          git pull origin main --rebase --autostash || true
          
          # Push FORÇADO (apenas para este repositório de stats)
          git push origin main --force-with-lease
          
          echo "✅ Atualização concluída com sucesso!"